AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/**/*'
    - 'spec/**/*'
    - 'config/application.rb'
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/initializers/wrap_parameters.rb'
    - 'config/initializers/assets.rb'
    - 'config/environments/development.rb'
    - 'config/environments/production.rb'
    - 'config/environments/test.rb'
    - 'Rakefile'
    - 'Procfile'

